In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [22]:
sal=pd.read_csv('/content/salaries (1).csv')
sal

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [23]:
sal.columns

Index(['company', 'job', 'degree', 'salary_more_then_100k'], dtype='object')

In [24]:
inputs=sal.drop('salary_more_then_100k',axis='columns')
target=sal['salary_more_then_100k']
inputs

company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [25]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

#Add new column to existing dataframe

In [28]:
inputs['company_n']=le_company.fit_transform(inputs['company'])
inputs['job_n']=le_company.fit_transform(inputs['job'])
inputs['degree_n']=le_company.fit_transform(inputs['degree'])
inputs.head()

company                  job     degree  company_n  job_n  degree_n
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

In [29]:
inputs_n=inputs.drop(['company','job','degree'],axis='columns')
inputs_n

company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [30]:
from sklearn import tree

In [31]:
model=tree.DecisionTreeClassifier()

In [32]:
model.fit(inputs_n,target)

DecisionTreeClassifier()

In [33]:
model.score(inputs_n,target)

1.0

In [35]:
model.predict_proba([[2,2,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([[1., 0.]])

In [36]:
model.predict([[2,2,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

###TiTanic Survival

In [49]:
tit=pd.read_csv('/content/titanic (1).csv')
tit

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [50]:
tit.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [51]:
tit=tit.drop(['PassengerId', 'Name', 'SibSp','Parch', 'Ticket',  'Cabin', 'Embarked'],axis='columns')
tit.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [52]:
dummies=pd.get_dummies(tit.Sex)
dummies.astype(int)

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [53]:
tit_n=pd.concat([tit,dummies.astype(int)],axis='columns')
tit_n

Survived  Pclass     Sex   Age     Fare  female  male
0           0       3    male  22.0   7.2500       0     1
1           1       1  female  38.0  71.2833       1     0
2           1       3  female  26.0   7.9250       1     0
3           1       1  female  35.0  53.1000       1     0
4           0       3    male  35.0   8.0500       0     1
..        ...     ...     ...   ...      ...     ...   ...
886         0       2    male  27.0  13.0000       0     1
887         1       1  female  19.0  30.0000       1     0
888         0       3  female   NaN  23.4500       1     0
889         1       1    male  26.0  30.0000       0     1
890         0       3    male  32.0   7.7500       0     1

[891 rows x 7 columns]

In [54]:
tit_n=tit_n.drop(['Sex'],axis='columns')
tit_n

Survived  Pclass   Age     Fare  female  male
0           0       3  22.0   7.2500       0     1
1           1       1  38.0  71.2833       1     0
2           1       3  26.0   7.9250       1     0
3           1       1  35.0  53.1000       1     0
4           0       3  35.0   8.0500       0     1
..        ...     ...   ...      ...     ...   ...
886         0       2  27.0  13.0000       0     1
887         1       1  19.0  30.0000       1     0
888         0       3   NaN  23.4500       1     0
889         1       1  26.0  30.0000       0     1
890         0       3  32.0   7.7500       0     1

[891 rows x 6 columns]

In [55]:
X=tit_n.drop(['Survived'],axis='columns')
X

Pclass   Age     Fare  female  male
0         3  22.0   7.2500       0     1
1         1  38.0  71.2833       1     0
2         3  26.0   7.9250       1     0
3         1  35.0  53.1000       1     0
4         3  35.0   8.0500       0     1
..      ...   ...      ...     ...   ...
886       2  27.0  13.0000       0     1
887       1  19.0  30.0000       1     0
888       3   NaN  23.4500       1     0
889       1  26.0  30.0000       0     1
890       3  32.0   7.7500       0     1

[891 rows x 5 columns]

In [56]:
y=tit_n.Survived

In [57]:
from sklearn.tree import DecisionTreeClassifier

In [58]:
model1=DecisionTreeClassifier()

In [59]:
model1.fit(X,y)

DecisionTreeClassifier()

In [60]:
model1.score(X,y)

0.8428731762065096

In [64]:
model1.predict([[3,20.0,100.2500,0,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])